name: TranslationChecker

on: pull_request

jobs:
  check:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      
    - id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'

    - name: Check Translation
      run: .\TranslationChecker.exe "${{ steps.files.outputs.all }}"
