name: Steam Translation Verifier

on: 
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  verify:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Verify
      run: powershell .\VerifySteamTranslations.ps1
